version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_4ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_4ban_static:/data/static/
      - gis_4ban_media:/data/media/

  django:
    image: gis_4ban_django:3
    networks:
      - gis_4ban_network
    volumes:
      - gis_4ban_static:/home/GIS_PHU/staticfiles/
      - gis_4ban_media:/home/GIS_PHU/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_4ban_network
    volumes:
    - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234




networks:
  gis_4ban_network:

volumes:
  gis_4ban_static:
  gis_4ban_media:
  gis_mariadb: